### ISSUE TITLE
[ERR] Account store name not found in main.js

### ISSUE THREAD

**Issue by Fadi002** [XielQs/httptoolkit-pro-patcher#18]
[+] Starting HTTP Toolkit...
[+] Done

[Patcher] Selected temp path: C:\Users\xxxxx\AppData\Local\Temp\httptoolkit-patch
[Patcher] Server listening on port 5067
[Patcher] Request to: /?authToken=84e671ab-996f-4d2b-92c9-22869efb4405&desktopVersion=1.12.6
[Patcher] File not changed, serving from temp path
[Patcher] Request to: /fonts.css
[Patcher] Request to: /mockttp.js
Config checked in 31 ms
Certificates setup in 8 ms
Standalone server started in 6 ms
Server started in 23 ms
Total startup took 68 ms
[Patcher] File not changed, serving from temp path
[Patcher] File not changed, serving from temp path
[Patcher] Request to: /apis.js
[Patcher] Request to: /vendors-node_modules_ajv_dist_ajv_js-node_modules_base64-js_index_js-node_modules_http-encodi-0d88b4.js
[Patcher] Request to: /vendors-node_modules_bn_js_lib_bn_js-node_modules_path-browserify_index_js.js
[Patcher] Request to: /a219baaae146da8ee8f5.png
[Patcher] Request to: /vendors-node_modules_ethersproject_abi_lib_esm_abi-coder_js-node_modules_fortawesome_free-bra-a48d34.js
[Patcher] Request to: /main.js
[Patcher] File not found in temp path, downloading
[Patcher] File not changed, serving from temp path
[Patcher] File not changed, serving from temp path
[Patcher] File not changed, serving from temp path
[Patcher] File not changed, serving from temp path
[Patcher] File not changed, serving from temp path
[Patcher] Patching main.js
[Patcher] [ERR] Account store name not found in main.js

**Comment by XielQs** [comment]
try updating your app to 1.19

**Comment by Fadi002** [comment]
worked thanks
