### ISSUE TITLE
Fix path

### ISSUE THREAD

**Issue by Vladik01-11** [XielQs/httptoolkit-pro-patcher#2]
path.join('/opt', 'httptoolkit')
->
path.join('/opt', 'HTTP Toolkit')
![Снимок экрана от 2024-05-26 00-23-14](https://github.com/XielQs/httptoolkit-pro-patcher/assets/70571714/5859fd4e-20d5-410d-af27-63c23df08096)

**Comment by XielQs** [comment]
Fixed ❤️
