### ISSUE TITLE
Initialization failed - background updates & cached/offline startup will be unavailable

### ISSUE THREAD

**Issue by lovefool1369a** [XielQs/httptoolkit-pro-patcher#21]
Recently I got "Initialization failed - background updates & cached/offline startup will be unavailable" message after raunching program, but the program works fine tho.
I have upgraded 1.18.1 to 1.19.0, updated npm, but no change.

Platform Windows11 22H2

=== HTTP toolkit last-run.log ===

httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.19.0
ERROR: Bad HTTP status: 0 
WARN: Enqueued failed request for retry in 6000
(node:3120) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Browser cache updated
WARN: Service worker registration failed
INFO: Reporting error: Initialization failed - background updates & cached/offline startup will be unavailable [object Object]
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.19.0
ERROR: Uncaught (in promise) TypeError: Failed to register a ServiceWorker for scope ('http://localhost:5067/') with script ('http://localhost:5067/ui-update-worker.js'): A bad HTTP response code (404) was received when fetching the script.
INFO: Previous server version was 1.19.0
ERROR: Bad HTTP status: 0 
WARN: Enqueued failed request for retry in 12000
ERROR: Bad HTTP status: 0 
WARN: Enqueued failed request for retry in 24000
ERROR: Bad HTTP status: 0 
WARN: Enqueued failed request for retry in 48000
ERROR: Bad HTTP status: 0 
WARN: Enqueued failed request for retry in 96000

**Comment by XielQs** [comment]
fixed!
