### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@electron/asar' imported from

### ISSUE THREAD

**Issue by belovolll** [XielQs/httptoolkit-pro-patcher#22]
<img width="1509" alt="image" src="https://github.com/user-attachments/assets/f36c489d-f0cf-4976-b274-0fdc093e8b39">

**Comment by XielQs** [comment]
do npm install

**Comment by belovolll** [comment]
already installed via homebrew, "brew install node"

**Comment by XielQs** [comment]
"brew install node" installs nodejs not packages

**Comment by belovolll** [comment]
thanks's it's works!!
