### ISSUE TITLE
the white screen in the program after "sudo node . patch"

### ISSUE THREAD

**Issue by listmen001** [XielQs/httptoolkit-pro-patcher#24]
On 04.11.2024, the program worked fine with the patch.
and already on 05.11.2024, a gray screen appears at startup. 
Reinstalling the patch does nothing.
Changing the IP doesn't do anything either.

Undo the changes and the program works.

Master, please help me)

**Comment by Dejavu666** [comment]
try updating your Node.js version to the latest version

**Comment by Dejavu666** [comment]
> On 04.11.2024, the program worked fine with the patch. and already on 05.11.2024, a gray screen appears at startup. Reinstalling the patch does nothing. Changing the IP doesn't do anything either.
> 
> Undo the changes and the program works.
> 
> Master, please help me)

Update Node.js v22.x and your problem is solved

**Comment by listmen001** [comment]
> Node.js v22

It works now!
Thanks a lot for the bug fixes!

P.S.: I need to find time for a deeper study of JS as soon as possible. This knowledge is becoming more and more necessary now.

**Comment by listmen001** [comment]
> Same issue, please guide me how to fix it. I updated nodejs to v 22.11.0

I think it's better to undo the changes or delete the program with all the components, update NodeJS, install the program and add the patch again.

personally, I did about that myself.

**Comment by kane1619** [comment]
> > Та же проблема, пожалуйста, подскажите, как ее исправить. Я обновил nodejs до версии 22.11.0
> 
> Я думаю, что лучше отменить изменения или удалить программу со всеми компонентами, обновить NodeJS, установить программу и добавить патч заново.
> 
> Лично я так и сделал.

Даже после выполненных шагов, проблема остается.

**Comment by NoamHarel1** [comment]
Same problem here, tried to reinstall both the app and patcher, didn’t help.

**Comment by fawyrad** [comment]
> > On 04.11.2024, the program worked fine with the patch. and already on 05.11.2024, a gray screen appears at startup. Reinstalling the patch does nothing. Changing the IP doesn't do anything either.
> > Undo the changes and the program works.
> > Master, please help me)
> 
> Update Node.js v22.x and your problem is solved

My Node.js already v22.x but the problem with blank white screen still appeared. #Windows 10

**Comment by NoNo8111** [comment]
I am using 1.19.1 and tried both node 22 or latest 23 but also blank screen after patching.

**Comment by XielQs** [comment]
check https://github.com/XielQs/httptoolkit-pro-patcher/issues/26#issuecomment-2465143167
