### ISSUE TITLE
won't open

### ISSUE THREAD

**Issue by ilpiruz** [XielQs/httptoolkit-pro-patcher#30]
the new patch worked a little, and then it doesn't work anymore 

![image](https://github.com/user-attachments/assets/8ed39e56-e7e9-4d22-957c-75ffea0fe268)

**Comment by ilpiruz** [comment]
what's even more strange is that if i go to the png (localhost:5067/a219baaae146da8ee8f5.png) it opens the right png

**Comment by ilpiruz** [comment]
the console looks like this: 
![image](https://github.com/user-attachments/assets/77036dea-8666-4c10-84ee-3197447683e1)

**Comment by XielQs** [comment]
duplicate of #26
