### ISSUE TITLE
HTTP Toolkit: Not Found

### ISSUE THREAD

**Issue by raedev** [XielQs/httptoolkit-pro-patcher#4]
After I apply the patch, the tooklit tips: Not Found, like this picture.

app version: `1.17.2`

![20240702160832](https://github.com/XielQs/httptoolkit-pro-patcher/assets/37961228/558781bd-165f-4737-b9f0-7ae3372817fd)

**Comment by XielQs** [comment]
Uh, can you send me a screenshot of developer tools network tab?

**Comment by raedev** [comment]
Yes, of course!

![image](https://github.com/XielQs/httptoolkit-pro-patcher/assets/37961228/c05fb7cc-30b3-48fb-990b-316cf8e4f1a4)

**Comment by raedev** [comment]
![image](https://github.com/XielQs/httptoolkit-pro-patcher/assets/37961228/34f4c967-b444-4d11-a6b1-5eb481bb1399)

**Comment by XielQs** [comment]
that's weird, can you show me the httptoolkit log (use command: start "C:\Users\rae\AppData\Local\Programs\httptoolkit\HTTP Toolkit.exe")

**Comment by raedev** [comment]
There's nothing in the `..\Temp\httptoolkit-patch` folder. Is it an administrator permission issue?

![image](https://github.com/XielQs/httptoolkit-pro-patcher/assets/37961228/07ed2e58-9d16-4ef1-829a-07c1ea57b461)

**Comment by XielQs** [comment]
it says no internet connection maybe your system proxy is blocking HEAD requests to google.com or something else?

**Comment by XielQs** [comment]
ohh i see in china google is blocked, i will change it to httptoolkit.app

**Comment by raedev** [comment]
oh, I only use a system proxy to access the network, because you can't access google in China. 
Can this patcher use a system proxy?

**Comment by raedev** [comment]
I changed the `www.google.com` to the `www.baidu.com`, and now it can be opened normally! 

`const hasInternet = () => request('HEAD', 'https://www.baidu.com').then(r => r.statusCode >= 200 && r.statusCode < 400).catch(() => false)`

Thanks~ ❤️

**Comment by XielQs** [comment]
i'm currently changing the patcher and adding a proxy support too!

**Comment by XielQs** [comment]
fixed with [761c70f](https://github.com/XielQs/httptoolkit-pro-patcher/commit/761c70f62141a10c7009bec88da15cbfdff34904) ❤️
