### ISSUE TITLE
TypeError: email.replaceAll is not a function

### ISSUE THREAD

**Issue by germcosti** [XielQs/httptoolkit-pro-patcher#5]
I'm getting this error when running the patcher

file:///C:/httptoolkit-pro-patcher/index.js:103
    .replace('const APP_URL =', `// ------- Injected by HTTP Toolkit Patcher -------\nconst email = \`${email.replaceAll('`', '\\`')}\`\n${patch}\n// ------- End patched content -------\nconst APP_URL =`)
                                                                                                              ^

TypeError: email.replaceAll is not a function
    at patchApp (file:///C:/httptoolkit-pro-patcher/index.js:103:111)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async file:///C:/httptoolkit-pro-patcher/index.js:130:5

**Comment by XielQs** [comment]
clone repo (or use `git pull` you know) and try again, if that didn't work then provide a screenshot of error please ❤️

**Comment by germcosti** [comment]
It works now thank you! :)

**Comment by XielQs** [comment]
Uh, can you send me a screenshot of your terminal using `node . patch`

**Comment by germcosti** [comment]
Yes here it is. I tried on a different PC as well and it did the same
![Screenshot_26](https://github.com/XielQs/httptoolkit-pro-patcher/assets/174597659/7c7e57f7-dc30-40fb-982f-2ca84fb16bce)

**Comment by XielQs** [comment]
can you go to httptoolkit directory and open a cmd on it then start "HTTP Toolkit exe" and share the screenshot

**Comment by germcosti** [comment]
Nothing shows up in cmd, but the app is running in task manager. If I node . restore the app  opens fine

**Comment by germcosti** [comment]
After restoring the patch, uninstalling node.js and reinstalling node.js and patching the app it now works

**Comment by XielQs** [comment]
that's weird, maybe cause of nodejs version?

**Comment by XielQs** [comment]
closing for now
