### ISSUE TITLE
Cannot launch HTTP Toolkit after patching

### ISSUE THREAD

**Issue by RaphxelS** [XielQs/httptoolkit-pro-patcher#6]
Hello,
After the patch, the app doesn't open.

Spec:
Win10 22H2
HTTP Toolkit v1.18.0

**Comment by XielQs** [comment]
Can you share a screenshot of your cmd after applying the patch?

**Comment by RaphxelS** [comment]
![image](https://github.com/XielQs/httptoolkit-pro-patcher/assets/100469363/7cfc5c9c-bbcd-42e3-ba0b-95ec9c8ef4d6)
Nothing happen after the node . start

**Comment by XielQs** [comment]
can you cd into httptoolkit directory and start httptoolkit directly from cmd?

cd %localappdata%\Programs\httptoolkit
"HTTP Toolkit.exe"

**Comment by RaphxelS** [comment]
Nothing happens

**Comment by XielQs** [comment]
what is your nodejs version?

**Comment by RaphxelS** [comment]
C:\Users\Raphael>node --version
v18.16.0

**Comment by XielQs** [comment]
maybe try reinstalling node js?

**Comment by XielQs** [comment]
and try the latest version of program

**Comment by IrvanWijayaSardam** [comment]
Having the same issue right here

**Comment by XielQs** [comment]
can you do "node . start" and share a screenshot?

**Comment by MestreKarin** [comment]
It's working like a charm. My specs:

Windows 11 Pro.
Patched both 1.17.2 and 1.18.0.
Node v20.7.0

I only modified the `appPath` in `index.js` because I downloaded the standalone version.

![image](https://github.com/user-attachments/assets/8631fd44-202b-42c7-9cc7-b9b34c1f9c11)

May I ask: isn't possible to enable this button? I thought it was enabled in pro.

![image](https://github.com/user-attachments/assets/8dc2096c-98fa-4c11-8a3b-41a9f3d5afcb)

Anyways, thank you man 👍

**Comment by IrvanWijayaSardam** [comment]
![image](https://github.com/user-attachments/assets/b3794016-db06-4d9a-bab9-bf446a2e18c5)
got this error, http toolkit 18.1.0, node version on the image

**Comment by XielQs** [comment]
> It's working like a charm. My specs:
> 
> Windows 11 Pro.
> Patched both 1.17.2 and 1.18.0.
> Node v20.7.0
> 
> I only modified the `appPath` in `index.js` because I downloaded the standalone version.
> 
> ![image](https://github.com/user-attachments/assets/8631fd44-202b-42c7-9cc7-b9b34c1f9c11)
> 
> May I ask: isn't possible to enable this button? I thought it was enabled in pro.
> 
> ![image](https://github.com/user-attachments/assets/8dc2096c-98fa-4c11-8a3b-41a9f3d5afcb)
> 
> Anyways, thank you man 👍

I think it is a httptoolkit bug, probably they will fix it soon

**Comment by XielQs** [comment]
> ![image](https://github.com/user-attachments/assets/b3794016-db06-4d9a-bab9-bf446a2e18c5)
> got this error, http toolkit 18.1.0, node version on the image

Maybe restore the patch and upgrade the npm version and try again?

**Comment by IrvanWijayaSardam** [comment]
now it's working, just reinstall the HTTP Toolkit , and try patch again, i'm using this node version
![image](https://github.com/user-attachments/assets/d8c1a5d9-4d8a-48f1-a508-70c382ab8baf)

**Comment by XielQs** [comment]
yea i think i can never understand that, but good to see that it's working!

**Comment by m7zr** [comment]
> It's working like a charm. My specs:
> 
> Windows 11 Pro. Patched both 1.17.2 and 1.18.0. Node v20.7.0
> 
> I only modified the `appPath` in `index.js` because I downloaded the standalone version.
> 
> ![image](https://private-user-images.githubusercontent.com/19618186/348446722-8631fd44-202b-42c7-9cc7-b9b34c1f9c11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5ODMwMTAsIm5iZiI6MTcyMDk4MjcxMCwicGF0aCI6Ii8xOTYxODE4Ni8zNDg0NDY3MjItODYzMWZkNDQtMjAyYi00MmM3LTljYzctYjliMzRjMWY5YzExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDE4NDUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhZDNiMGJiMTY2NWZiMWEwNjM2NjFhZmQyOTE2NzA0MDBlMDFmNThiZWQyNzRkZTJiN2EwMGJhZjYwZDk4Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.veE5lMCe0qFpLJqdq5Pn2KhFI8ZTEUdlqCW9AgMcnVU)
> 
> May I ask: isn't possible to enable this button? I thought it was enabled in pro.
> 
> ![image](https://private-user-images.githubusercontent.com/19618186/348447013-8dc2096c-98fa-4c11-8a3b-41a9f3d5afcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5ODMwMTAsIm5iZiI6MTcyMDk4MjcxMCwicGF0aCI6Ii8xOTYxODE4Ni8zNDg0NDcwMTMtOGRjMjA5NmMtOThmYS00YzExLThhM2ItNDFhOWYzZDVhZmNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDE4NDUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmODQ5YmU1MThhOGU0NjUxMWU5OTUxZWM3OWQ0MTg5MDc3MWU2MDJlYWJlNTBmN2JiMTJmYmEyNzFhZGEzZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2n5BCX7Hwk56xzJ1--M7sdZlDja5_J3nC424L2QUQao)
> 
> Anyways, thank you man 👍

hit the + and you will see everyting 
![image](https://github.com/user-attachments/assets/22b62013-dded-41fe-baa7-de4e0ce34caf)

**Comment by XielQs** [comment]
Closing it due to inactivity, if anyone encounters an error with this subject I'm going to reopen it!!

**Comment by pergolafabio** [comment]
Hey, installed v1.18.1 
but if i patch, the program never loads, it waits on this screen:
![image](https://github.com/user-attachments/assets/bdbf5480-80a9-4532-a5da-ea4770451a67)

i filled : dummy@example.com , should i use something else?

node version 20.15.1
npm version 10.7.0 , 

i dont get any error when patching?

![image](https://github.com/user-attachments/assets/11a0b011-5bc0-4cd3-85b4-6339425287c5)

**Comment by pergolafabio** [comment]
if i do : node . start : 

![image](https://github.com/user-attachments/assets/c0912bde-f489-423a-8c05-f9165613a241)

**Comment by XielQs** [comment]
can you run `node . start` and provide a screenshot?

**Comment by pergolafabio** [comment]
i tried restore, did patch again, and now it indeed works!!

not sure why it didnt work first time? i now used a different email address? could that cause it? i used dummy@example.com at first :-)

**Comment by reporter29** [comment]
I was running into the same issue and the suggestions from @IrvanWijayaSardam and @pergolafabio did not fix it. My fix was to

1. `node . restore` (or skip this if you haven't patched yet)
2. `node . start` and let toolkit fully load, then `ctrl + C` (I noticed some files were being downloaded that didn't happen during my initial start after patching the application for the first time)
3. `node . patch`
4. `node . start` or open the application directly via shortcut.

Just putting this here in case it helps anyone else.

**Comment by XielQs** [comment]
> I was running into the same issue and the suggestions from @IrvanWijayaSardam and @pergolafabio did not fix it. My fix was to
> 
>     1. `node . restore` (or skip this if you haven't patched yet)
> 
>     2. `node . start` and let toolkit fully load, then `ctrl + C` (I noticed some files were being downloaded that didn't happen during my initial start after patching the application for the first time)
> 
>     3. `node . patch`
> 
>     4. `node . start` or open the application directly via shortcut.
> 
> 
> Just putting this here in case it helps anyone else.

Thank you for the information! I'm still not entirely sure about the source of the error. Despite trying it multiple times on different devices and machines without any issues, it somehow worked for me without any errors or bugs.

**Comment by TheRadziu** [comment]
> ![image](https://private-user-images.githubusercontent.com/43365154/348454193-b3794016-db06-4d9a-bab9-bf446a2e18c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NDI5NjcsIm5iZiI6MTcyMjQ0MjY2NywicGF0aCI6Ii80MzM2NTE1NC8zNDg0NTQxOTMtYjM3OTQwMTYtZGIwNi00ZDlhLWJhYjktYmY0NDZhMmUxOGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDE2MTc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NDc0MDIwZTQ1YWY0YThkMmRlNmFkYTIyMzRkOTg1NGEwMGRiMDA3YmZmNDYyYjEzMjBhMDczZDQxMGFkZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ey8NtQrWxU7b2xN4IatIQByQCruIbF9FjMLAy8PYc5k) got this error, http toolkit 18.1.0, node version on the image

i have exact same issue, latest versions of node.js and http toolkit. Any solutions to this?

**Comment by Momo-Belia-l** [comment]
Hello, unfortunately the Pro patch no longer seems to work with the latest version, it no longer opens for me. Version: 1.19.0, Platform: Windows. I tried several times to use an old version but it doesn't work. I would be very happy about an update of the patch or tips on how to fix it.

**Comment by XielQs** [comment]
> ![image](https://github.com/user-attachments/assets/6d2788e9-e9dd-49f3-9dd3-ff413cf3aad6)
> 
> Gotting this blank screen when done patching 

it looks like a HTTP Toolkit bug, try reinstalling
