### ISSUE TITLE
Is the patch permanently? 

### ISSUE THREAD

**Issue by h9nt** [XielQs/httptoolkit-pro-patcher#8]

**Comment by XielQs** [comment]
What did you mean?

**Comment by h9nt** [comment]
> What did you mean?

the features that get unlocked

**Comment by XielQs** [comment]
> > What did you mean?
> 
> the features that get unlocked 

well, if HTTP Toolkit downloads an update you should maybe re-patch again the app but it's permanent

**Comment by h9nt** [comment]
> > > What did you mean?
> > 
> > 
> > the features that get unlocked
> 
> well, if HTTP Toolkit downloads an update you should maybe re-patch again the app but it's permanent

allright thanks for the answer!

**Comment by XielQs** [comment]
closing!!
